trigger:
  branches:
    include:
      - main

variables:
  BUILD_FOLDER: 'dist'   # <-- Vite uses 'dist'. Change to 'build' for CRA.

pool:
  name: Default

steps:
  # 1️⃣ Use Node.js
  - checkout: self
    fetchDepth: 1
  - task: NodeTool@0
    inputs:
      versionSpec: '22.x'
    displayName: 'Use Node.js 22'

  # 2️⃣ Install dependencies and build React app
  - script: |
      npm ci
      npm run build
    displayName: 'Install and build React app'

  - powershell: |
      Write-Host "=== Debug: list $(Build.SourcesDirectory) ==="
      Get-ChildItem -Path "$(Build.SourcesDirectory)" -Force -Recurse -Depth 2 | Format-Table -AutoSize
    displayName: 'List repo contents after build (debug)'
    
  # 3️⃣ Archive build output
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/build.zip'
      replaceExistingArchive: true
    displayName: 'Archive build folder'

  # 4️⃣ Deploy to Azure App Service
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'azure-connection'  # Name of your Service Connection
      appName: 'cwretailfe'                  # Your App Service name
      package: '$(Build.ArtifactStagingDirectory)/build.zip'
      runtimeStack: 'NODE|22-lts'
    displayName: 'Deploy React app to Azure Web App'
