trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # 1️⃣ Use Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '22.x'
    displayName: 'Use Node.js 22'

  # 2️⃣ Install dependencies and build React app
  - script: |
      npm ci
      npm run build
    displayName: 'Install and build React app'

  # 3️⃣ Archive build output
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/build.zip'
      replaceExistingArchive: true
    displayName: 'Archive build folder'

  # 4️⃣ Deploy to Azure App Service
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'azure-connection'  # Name of your Service Connection
      appName: 'cwretailfe'                  # Your App Service name
      package: '$(Build.ArtifactStagingDirectory)/build.zip'
      runtimeStack: 'NODE|22-lts'
    displayName: 'Deploy React app to Azure Web App'
