trigger:
  branches:
    include:
      - main

variables:
  BUILD_FOLDER: 'dist'   # <-- Vite => 'dist'. If CRA, change to 'build'.

pool:
  name: Default   # <-- make sure this matches the exact agent pool name where your agent is Online

steps:
- checkout: self
  fetchDepth: 1

- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Use Node.js 22'

- script: |
    npm ci
    npm run build
  displayName: 'Install and build React app'

- powershell: |
    Write-Host "=== Debug: list the build output directory ==="
    $folder = "$(System.DefaultWorkingDirectory)\$(BUILD_FOLDER)"
    Write-Host "Archive target: $folder"
    if (Test-Path $folder) {
      Get-ChildItem -Path $folder -Recurse -Depth 2 | Format-Table -AutoSize
    } else {
      Write-Host "ERROR: build output folder not found: $folder"
      Get-ChildItem -Path "$(System.DefaultWorkingDirectory)" -Force -Recurse -Depth 1 | Format-Table -AutoSize
      exit 1
    }
  displayName: 'List repo contents after build (debug)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/$(BUILD_FOLDER)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/build.zip'
    replaceExistingArchive: true
  displayName: 'Archive build folder'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azure-connection'  # <-- your Service Connection name
    appName: 'cwretailfe'                  # <-- your App Service name
    package: '$(Build.ArtifactStagingDirectory)/build.zip'
    runtimeStack: 'NODE|22-lts'
  displayName: 'Deploy to Azure Web App'
