// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibwxwrhmvhdluctucxiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlid3h3cmhtdmhkbHVjdHVjeGl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNDc1NzMsImV4cCI6MjA2MzYyMzU3M30.pS3mhLSJwp5ZsLgWi_-uaxRDH7T9trmbaqEIwt4YclE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);